// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: inference/serve/pb/inference.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SamplingParams configures token sampling behavior.
type SamplingParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Temperature for sampling (0 = greedy/argmax).
	Temperature float32 `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Top-k sampling: only consider the k most likely tokens. 0 = disabled.
	TopK int32 `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// Top-p (nucleus) sampling: consider tokens with cumulative probability >= p. 0 = disabled.
	TopP float32 `protobuf:"fixed32,3,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	// Maximum number of tokens to generate. 0 = model default.
	MaxTokens     int32 `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplingParams) Reset() {
	*x = SamplingParams{}
	mi := &file_inference_serve_pb_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingParams) ProtoMessage() {}

func (x *SamplingParams) ProtoReflect() protoreflect.Message {
	mi := &file_inference_serve_pb_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingParams.ProtoReflect.Descriptor instead.
func (*SamplingParams) Descriptor() ([]byte, []int) {
	return file_inference_serve_pb_inference_proto_rawDescGZIP(), []int{0}
}

func (x *SamplingParams) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SamplingParams) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SamplingParams) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *SamplingParams) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type GenerateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The input prompt to generate from.
	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Optional sampling parameters. If not set, server defaults are used.
	SamplingParams *SamplingParams `protobuf:"bytes,2,opt,name=sampling_params,json=samplingParams,proto3" json:"sampling_params,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_inference_serve_pb_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_serve_pb_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_inference_serve_pb_inference_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetSamplingParams() *SamplingParams {
	if x != nil {
		return x.SamplingParams
	}
	return nil
}

type GenerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generated text. For streaming, each message contains a single token.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Total number of tokens generated so far (including this one).
	TokenCount int32 `protobuf:"varint,2,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	// Reason generation finished. Only set on the final message.
	// Values: "eos" (end of sequence), "max_tokens" (limit reached), "cancelled" (client cancelled).
	FinishReason  string `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_inference_serve_pb_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_serve_pb_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_inference_serve_pb_inference_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateResponse) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *GenerateResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type ModelInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfoRequest) Reset() {
	*x = ModelInfoRequest{}
	mi := &file_inference_serve_pb_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoRequest) ProtoMessage() {}

func (x *ModelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_serve_pb_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoRequest.ProtoReflect.Descriptor instead.
func (*ModelInfoRequest) Descriptor() ([]byte, []int) {
	return file_inference_serve_pb_inference_proto_rawDescGZIP(), []int{3}
}

type ModelInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable model name (e.g., "LLaMA 2 7B").
	ModelName string `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// Model architecture (e.g., "llama", "phi").
	Architecture string `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`
	// Quantization method (e.g., "Q4_0", "Q8_0", "F16").
	Quantization string `protobuf:"bytes,3,opt,name=quantization,proto3" json:"quantization,omitempty"`
	// Maximum context length in tokens.
	MaxContextLength int32 `protobuf:"varint,4,opt,name=max_context_length,json=maxContextLength,proto3" json:"max_context_length,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModelInfoResponse) Reset() {
	*x = ModelInfoResponse{}
	mi := &file_inference_serve_pb_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoResponse) ProtoMessage() {}

func (x *ModelInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_serve_pb_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoResponse.ProtoReflect.Descriptor instead.
func (*ModelInfoResponse) Descriptor() ([]byte, []int) {
	return file_inference_serve_pb_inference_proto_rawDescGZIP(), []int{4}
}

func (x *ModelInfoResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelInfoResponse) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *ModelInfoResponse) GetQuantization() string {
	if x != nil {
		return x.Quantization
	}
	return ""
}

func (x *ModelInfoResponse) GetMaxContextLength() int32 {
	if x != nil {
		return x.MaxContextLength
	}
	return 0
}

var File_inference_serve_pb_inference_proto protoreflect.FileDescriptor

const file_inference_serve_pb_inference_proto_rawDesc = "" +
	"\n" +
	"\"inference/serve/pb/inference.proto\x12\x02pb\"{\n" +
	"\x0eSamplingParams\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12\x13\n" +
	"\x05top_p\x18\x03 \x01(\x02R\x04topP\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\"f\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12;\n" +
	"\x0fsampling_params\x18\x02 \x01(\v2\x12.pb.SamplingParamsR\x0esamplingParams\"l\n" +
	"\x10GenerateResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vtoken_count\x18\x02 \x01(\x05R\n" +
	"tokenCount\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\x12\n" +
	"\x10ModelInfoRequest\"\xa8\x01\n" +
	"\x11ModelInfoResponse\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\"\n" +
	"\farchitecture\x18\x02 \x01(\tR\farchitecture\x12\"\n" +
	"\fquantization\x18\x03 \x01(\tR\fquantization\x12,\n" +
	"\x12max_context_length\x18\x04 \x01(\x05R\x10maxContextLength2\xc8\x01\n" +
	"\x10InferenceService\x127\n" +
	"\bGenerate\x12\x13.pb.GenerateRequest\x1a\x14.pb.GenerateResponse\"\x00\x12?\n" +
	"\x0eStreamGenerate\x12\x13.pb.GenerateRequest\x1a\x14.pb.GenerateResponse\"\x000\x01\x12:\n" +
	"\tModelInfo\x12\x14.pb.ModelInfoRequest\x1a\x15.pb.ModelInfoResponse\"\x00B\x1aZ\x18vexel/inference/serve/pbb\x06proto3"

var (
	file_inference_serve_pb_inference_proto_rawDescOnce sync.Once
	file_inference_serve_pb_inference_proto_rawDescData []byte
)

func file_inference_serve_pb_inference_proto_rawDescGZIP() []byte {
	file_inference_serve_pb_inference_proto_rawDescOnce.Do(func() {
		file_inference_serve_pb_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_serve_pb_inference_proto_rawDesc), len(file_inference_serve_pb_inference_proto_rawDesc)))
	})
	return file_inference_serve_pb_inference_proto_rawDescData
}

var file_inference_serve_pb_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_inference_serve_pb_inference_proto_goTypes = []any{
	(*SamplingParams)(nil),    // 0: pb.SamplingParams
	(*GenerateRequest)(nil),   // 1: pb.GenerateRequest
	(*GenerateResponse)(nil),  // 2: pb.GenerateResponse
	(*ModelInfoRequest)(nil),  // 3: pb.ModelInfoRequest
	(*ModelInfoResponse)(nil), // 4: pb.ModelInfoResponse
}
var file_inference_serve_pb_inference_proto_depIdxs = []int32{
	0, // 0: pb.GenerateRequest.sampling_params:type_name -> pb.SamplingParams
	1, // 1: pb.InferenceService.Generate:input_type -> pb.GenerateRequest
	1, // 2: pb.InferenceService.StreamGenerate:input_type -> pb.GenerateRequest
	3, // 3: pb.InferenceService.ModelInfo:input_type -> pb.ModelInfoRequest
	2, // 4: pb.InferenceService.Generate:output_type -> pb.GenerateResponse
	2, // 5: pb.InferenceService.StreamGenerate:output_type -> pb.GenerateResponse
	4, // 6: pb.InferenceService.ModelInfo:output_type -> pb.ModelInfoResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inference_serve_pb_inference_proto_init() }
func file_inference_serve_pb_inference_proto_init() {
	if File_inference_serve_pb_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_serve_pb_inference_proto_rawDesc), len(file_inference_serve_pb_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_serve_pb_inference_proto_goTypes,
		DependencyIndexes: file_inference_serve_pb_inference_proto_depIdxs,
		MessageInfos:      file_inference_serve_pb_inference_proto_msgTypes,
	}.Build()
	File_inference_serve_pb_inference_proto = out.File
	file_inference_serve_pb_inference_proto_goTypes = nil
	file_inference_serve_pb_inference_proto_depIdxs = nil
}
